spring:
  config:
    import: >
      classpath:/configurations/main.yaml,
      classpath:/configurations/db.yaml,
      classpath:/configurations/eureka.yaml,
      classpath:/configurations/flyway.yaml,
      classpath:/configurations/instance.yaml,
      classpath:/configurations/redis.yaml,
      classpath:/configurations/rabbitmq.yaml
  application:
    name: auth-service
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /auth
  port: 0
migration-path: user
rabbitmq:
  destination:
    auth: authQueue
    registration: registrationQueue