spring:
  application:
    name: auth-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    #url: jdbc:postgresql://localhost:5432/user_db #For IDEA Debug
    url: jdbc:postgresql://db:5432/user_db #For Docker
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka # for Docker
      # http://eureka:password@localhost:8761/eureka for IDEA
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}