spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://main-service/
          predicates:
            - Path=/main/**
        - id: admin-service
          uri: lb://admin-service/
          predicates:
            - Path=/admin/**
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
        - id: spring-boot-admin
          uri: lb://spring-boot-admin/
          predicates:
            - Path=/sba/**
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**
    config:
      profile: eureka
      name: config
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  forward-headers-strategy: framework
  port: 8080