spring:
  config:
    import: >
      classpath:/configurations/main.yaml,
      classpath:/configurations/eureka.yaml
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: lb://main-service/
          predicates:
            - Path=/main/**
        - id: admin-service
          uri: lb://admin-service/
          predicates:
            - Path=/admin/**
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
        - id: music-service
          uri: lb://music-service/
          predicates:
            - Path=/music/**
        - id: spring-boot-admin
          uri: lb://spring-boot-admin/
          predicates:
            - Path=/sba/**
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  forward-headers-strategy: framework
  port: 8080
jwt:
  auth:
    converter:
      resource-id: demo-client
      principal-attribute: preferred-username
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: admin-service
        url: /admin/v3/api-docs
      - name: auth-service
        url: /auth/v3/api-docs
      - name: main-service
        url: /main/v3/api-docs
      - name: music-service
        url: /music/v3/api-docs