spring:
  boot:
    admin:
      discovery:
        ignored-services:
          - api-gateway
  security:
    user:
      name: admin
      password: $2a$04$aFsghUjX04PI3hRbjnanKO9adBXflUy401P0iTnMtmb5hufRpdvXC
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      profile: eureka, instance
      name: config
  application:
    name: spring-boot-admin
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /sba
  port: 8585