spring:
  config:
    import: >
      classpath:/configurations/main.yaml,
      classpath:/configurations/eureka.yaml,
      classpath:/configurations/instance.yaml
  boot:
    admin:
      discovery:
        ignored-services:
          - api-gateway
  security:
    user:
      name: admin
      password: $2a$04$aFsghUjX04PI3hRbjnanKO9adBXflUy401P0iTnMtmb5hufRpdvXC
  application:
    name: spring-boot-admin
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /sba
  port: 8585