spring:
  config:
    name: com.admin.controller
  flyway:
    enabled: true
    locations: classpath:db.migration
  application:
    name: admin-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db #For IDEA Debug
    #url: jdbc:postgresql://db:5432/user_db #For Docker
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true
server:
  servlet:
    context-path: /admin
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      #defaultZone: http://eureka:password@discovery-server:8761/eureka # for Docker
      defaultZone: http://eureka:password@localhost:8761/eureka # for IDEA
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}