spring:
  config:
    import: >
      classpath:/configurations/main.yaml,
      classpath:/configurations/db.yaml,
      classpath:/configurations/eureka.yaml,
      classpath:/configurations/flyway.yaml,
      classpath:/configurations/instance.yaml,
      classpath:/configurations/redis.yaml
  application:
    name: admin-service
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /admin
  port: 0
migration-path: user